---
title: "Nested Random Effects"
output: html_notebook
---

Based on [this tutorial](https://www.jaredknowles.com/journal/2013/11/25/getting-started-with-mixed-effect-models-in-r), data by Jon Starkweather at the University of North Texas.

```{r}
library(lme4)  # load library
lmm.data <- read.table("http://math-info.hse.ru/f/2018-19/ling-data/lmm.data.txt", 
    header = TRUE, sep = ",", na.strings = "NA", dec = ".", strip.white = TRUE)
# summary(lmm.data)
head(lmm.data)
```

```{r}
MLexamp.6 <- lmer(extro ~ open + agree + social + (1 | school), data = lmm.data)
summary(MLexamp.6)
```

```{r}
MLexamp.7 <- lmer(extro ~ open + agree + social + (1 | school) + (1 | class), 
    data = lmm.data)
summary(MLexamp.7)
```

```{r}
MLexamp.8 <- lmer(extro ~ open + agree + social + (1 | school) + (1 | school:class), data = lmm.data)
summary(MLexamp.8)
```

```{r}
MLexamp.8prime <- lmer(extro ~ open + agree + social + (1 | school/class), data = lmm.data)
summary(MLexamp.8prime)
```
```{r}
lmm.data %>% mutate(school_class=paste(school, class, sep="_")) -> lmm.data_with_interaction
lmm.data_with_interaction
```

```{r}
MLexamp.9 <- lmer(extro ~ open + agree + social + (1 | school) + (1 | school_class), data=lmm.data_with_interaction)
summary(MLexamp.9)
```